/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as GamesRouteImport } from './routes/games'
import { Route as CivicRouteImport } from './routes/civic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter/confirm'
import { Route as GamesFactOrFictionRouteImport } from './routes/games/fact-or-fiction'
import { Route as GamesDailyQuizRouteImport } from './routes/games/daily-quiz'
import { Route as GamesConnectionsRouteImport } from './routes/games/connections'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const CivicRoute = CivicRouteImport.update({
  id: '/civic',
  path: '/civic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesFactOrFictionRoute = GamesFactOrFictionRouteImport.update({
  id: '/fact-or-fiction',
  path: '/fact-or-fiction',
  getParentRoute: () => GamesRoute,
} as any)
const GamesDailyQuizRoute = GamesDailyQuizRouteImport.update({
  id: '/daily-quiz',
  path: '/daily-quiz',
  getParentRoute: () => GamesRoute,
} as any)
const GamesConnectionsRoute = GamesConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/civic': typeof CivicRoute
  '/games': typeof GamesRouteWithChildren
  '/test': typeof TestRoute
  '/games/connections': typeof GamesConnectionsRoute
  '/games/daily-quiz': typeof GamesDailyQuizRoute
  '/games/fact-or-fiction': typeof GamesFactOrFictionRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/civic': typeof CivicRoute
  '/games': typeof GamesRouteWithChildren
  '/test': typeof TestRoute
  '/games/connections': typeof GamesConnectionsRoute
  '/games/daily-quiz': typeof GamesDailyQuizRoute
  '/games/fact-or-fiction': typeof GamesFactOrFictionRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/civic': typeof CivicRoute
  '/games': typeof GamesRouteWithChildren
  '/test': typeof TestRoute
  '/games/connections': typeof GamesConnectionsRoute
  '/games/daily-quiz': typeof GamesDailyQuizRoute
  '/games/fact-or-fiction': typeof GamesFactOrFictionRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/civic'
    | '/games'
    | '/test'
    | '/games/connections'
    | '/games/daily-quiz'
    | '/games/fact-or-fiction'
    | '/newsletter/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/civic'
    | '/games'
    | '/test'
    | '/games/connections'
    | '/games/daily-quiz'
    | '/games/fact-or-fiction'
    | '/newsletter/confirm'
  id:
    | '__root__'
    | '/'
    | '/civic'
    | '/games'
    | '/test'
    | '/games/connections'
    | '/games/daily-quiz'
    | '/games/fact-or-fiction'
    | '/newsletter/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CivicRoute: typeof CivicRoute
  GamesRoute: typeof GamesRouteWithChildren
  TestRoute: typeof TestRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civic': {
      id: '/civic'
      path: '/civic'
      fullPath: '/civic'
      preLoaderRoute: typeof CivicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/fact-or-fiction': {
      id: '/games/fact-or-fiction'
      path: '/fact-or-fiction'
      fullPath: '/games/fact-or-fiction'
      preLoaderRoute: typeof GamesFactOrFictionRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/daily-quiz': {
      id: '/games/daily-quiz'
      path: '/daily-quiz'
      fullPath: '/games/daily-quiz'
      preLoaderRoute: typeof GamesDailyQuizRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/connections': {
      id: '/games/connections'
      path: '/connections'
      fullPath: '/games/connections'
      preLoaderRoute: typeof GamesConnectionsRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesConnectionsRoute: typeof GamesConnectionsRoute
  GamesDailyQuizRoute: typeof GamesDailyQuizRoute
  GamesFactOrFictionRoute: typeof GamesFactOrFictionRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesConnectionsRoute: GamesConnectionsRoute,
  GamesDailyQuizRoute: GamesDailyQuizRoute,
  GamesFactOrFictionRoute: GamesFactOrFictionRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CivicRoute: CivicRoute,
  GamesRoute: GamesRouteWithChildren,
  TestRoute: TestRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
